import {HOLIDAY_OPTIONS,GENERAL_HOLIDAY_VIBES,HOLIDAY_INTENSITIES,HOLIDAY_PALETTES,HOLIDAY_FASHION_INFLUENCE,HOLIDAY_PROP_MODES,HOLIDAY_ENVIRONMENTS,HOLIDAY_TYPOGRAPHY,HOLIDAY_BEAUTY} from './holidayData.js';
import {EXPRESSION_CATEGORIES,POSE_CATEGORIES,ALL_EXPRESSIONS,ALL_POSES} from './performanceData.js';
import {DESIGN_ARCHITECTURES,SUBJECT_PLACEMENTS,DETAIL_PLACEMENTS,VISUAL_DENSITIES} from './designData.js';
import {GAME_DAY_WORLD,gameDayDefaults} from './gameDayData.js';
const o=(...items)=>items;
export const SECTIONS=[
  {id:'her',label:'HER',icon:'💋',sub:'The Foundation',tag:'Define the foundation of your baddie.'},
  {id:'face',label:'FACE + HAIR',icon:'👩🏾',sub:'Beauty & Crown',tag:'Frame the face. Crown the whole vision.'},
  {id:'fashion',label:'FASHION',icon:'🧥',sub:'Clothes, Shoes, Bags',tag:'Style the look from silhouette to sole.'},
  {id:'attitude',label:'ATTITUDE',icon:'💃🏾',sub:'Pose, Energy, Vibe',tag:'Give her a point of view.'},
  {id:'art',label:'ART DIRECTION',icon:'⚡',sub:'The Creative Vision',tag:'Direct the image like the campaign is yours.'},
  {id:'production',label:'PRODUCTION',icon:'⚙',sub:'How It’s Made',tag:'Make the final recipe production-smart.'}
];
export const FIELDS={
  her:[
    ['world','WORLD','Lifestyle vibe','🌐',o('Surprise Me',GAME_DAY_WORLD,'Soft Baddie','Street Baddie','Luxury Baddie','Boss Baddie','Grown Woman Baddie','Glam Baddie','Chill Baddie','Pretty & Petty','Brunch Baddie','Vacation Baddie','Birthday Baddie','Beauty Mogul','Mom Baddie','Fitness Baddie','Alt Baddie','Goth Baddie','Retro Baddie','Futuristic Baddie','After Dark','Soft Boss Baddie','Street Luxury Baddie','Grown Woman Street Luxury','Vacation Glam','Alt Luxury','Cozy Baddie','Creative Baddie','Everyday Main Character')],
    ['holiday','HOLIDAY / CELEBRATION','Influence the story, never replace her','✦',HOLIDAY_OPTIONS],
    ['holidayVibe','HOLIDAY VIBE','Seasonal creative direction','♛',GENERAL_HOLIDAY_VIBES],
    ['holidayIntensity','HOLIDAY INTENSITY','How loudly it shows up','⚡',HOLIDAY_INTENSITIES],
    ['holidayPalette','HOLIDAY PALETTE','Never force cliché colors','◉',HOLIDAY_PALETTES],
    ['holidayFashion','HOLIDAY FASHION INFLUENCE','Keep fashion woman-first','🧥',HOLIDAY_FASHION_INFLUENCE],
    ['holidayProps','HOLIDAY PROPS','Story support, not clutter','◆',HOLIDAY_PROP_MODES],
    ['holidayEnvironment','HOLIDAY ENVIRONMENT','Scene-level influence','▧',HOLIDAY_ENVIRONMENTS],
    ['holidayTypography','HOLIDAY TYPOGRAPHY MODE','Coordinate with type settings','Aa',HOLIDAY_TYPOGRAPHY],
    ['holidayPhrase','HOLIDAY PHRASE','Optional — preserved exactly','✎','text'],
    ['holidayBeauty','HOLIDAY BEAUTY INFLUENCE','Grown, stylish, never costume makeup','💄',HOLIDAY_BEAUTY],
    ['holidayCustomPalette','CUSTOM HOLIDAY PALETTE','Three exact holiday colors','◉','colors'],
    ['age','ADULT AGE','Grown & fly','🧍🏾‍♀️',o('Surprise Me','20s','30s','40s','50s','60s','70+')],
    ['body','BODY PRESENTATION','Her shape','♟',o('Surprise Me','Petite','Slim','Midsize','Soft Curvy','Curvy','Plus-Size','Full-Figured','Voluptuous','Athletic','Tall & Statuesque','Soft & Rounded','Lean','Broad & Powerful','Pear-Shaped','Apple-Shaped','Hourglass','Straight / Column')],
    ['complexion','COMPLEXION','Her glow','✿',o('Deep Ebony','Deep Rich Brown','Dark Brown','Rich Mahogany','Medium-Deep Brown','Warm Brown','Golden Brown','Caramel Brown','Light Brown','Surprise Me')],
    ['bodyArt','BODY ART','Ink & expression','♨',o('None','Delicate Fine-Line Tattoo','Arm Tattoo','Shoulder Tattoo','Thigh Tattoo','Half Sleeve','Full Sleeve','Back Piece','Tiny Wrist Tattoo','Surprise Me')],
    ['occasion','OCCASION / LIFESTYLE','What we doin’?','♡',o('Brunch','Shopping Day','Girls Trip','Airport / Travel','Work / Boss','Date Night','Girls’ Night','Gallery Opening','Concert Night','Birthday Dinner','Creative Studio','Weekend Errands','Vacation Poolside','Rooftop Party','Surprise Me')],
    ['height','HEIGHT IMPRESSION','Visual stature','↕',o('Petite presence','Short presence','Average height','Tall presence','Statuesque','Surprise Me')],
    ['piercings','PIERCINGS','Personal details','✦',o('None','Classic ear piercings','Multiple ear stack','Nose stud','Septum accent','Brow accent','Surprise Me')]
  ],
  face:[
    ['hairFamily','HAIR FAMILY','Her crown','♛',o('Natural Afro','Tapered Afro','Defined Coils','Wash-and-Go','Twist-Out','Braid-Out','Locs','Faux Locs','Micro Locs','Knotless Braids','Box Braids','Boho Braids','Fulani-Inspired Braiding','Passion Twists','Marley Twists','Cornrows','Braided Ponytail','Braided Bun','Silk Press','Bob','Pixie','Finger Waves','Puff','Ponytail','Sculptural Updo','Short Natural Cut')],
    ['hairStyle','SPECIFIC STYLE','The detail','〰',o('Free-flowing','Half-up crown','High bun','Low sculptural bun','Side-swept','Layered bob','Braided topknot','Waist-sweeping','Asymmetrical crop','Bubble ponytail','Pinned halo','Face-framing tendrils','Surprise Me')],
    ['hairLength','HAIR LENGTH','Cropped to dramatic','↕',o('Buzzed','Cropped','Chin Length','Shoulder Length','Mid-Back','Waist Length','Extra Long','Surprise Me')],
    ['texture','TEXTURE','Hair finish','〽',o('Tight coils','Soft coils','Defined curls','Kinky-straight','Silky-straight','Crimped','Wavy','Braided texture','Loc texture','Surprise Me')],
    ['hairColor','HAIR COLOR','Crown color','◉',o('Natural Black','Soft Black','Espresso','Chestnut Brown','Copper','Burgundy','Honey Blonde','Platinum','Silver Gray','Salt & Pepper','Fantasy Berry','Surprise Me')],
    ['faceShape','FACE SHAPE','Facial structure','◇',o('Oval','Round','Heart','Square','Diamond','Long','Soft angular','Full-cheeked','Surprise Me')],
    ['eyes','EYES + BROWS','The gaze','◉',o('Almond eyes + arched brows','Round eyes + soft brows','Hooded eyes + lifted brows','Deep-set eyes + straight brows','Upturned eyes + feathered brows','Surprise Me')],
    ['makeup','MAKEUP','Beat direction','💄',o('Barely There','Natural','Soft Glam','Bronzed','Matte Glam','Dewy','Editorial','Retro','Smoky','Graphic Liner','Bold Lip','Monochromatic','Mature Sophisticated Glam','Colorful Beauty')],
    ['nails','NAILS','Length, shape, finish','💅🏾',o('Short natural gloss','Short square nude','Medium almond','Medium oval','Long coffin','Long stiletto','Sculptural editorial','Bare and buffed','Chrome finish','French detail','Graphic nail art','Surprise Me')],
    ['beautyDetails','BEAUTY DETAILS','Marks & freckles','✦',o('None','Beauty mark','Soft freckles','Beauty mark + freckles','Dimpled smile','Surprise Me')]
  ],
  fashion:[
    ['fashionDirection','FASHION DIRECTION','Her style language','✦',o('Streetwear','Street Luxury','Quiet Luxury','Soft Luxury','Grown Woman Streetwear','Executive','Business Chic','Creative Professional','Elevated Casual','Denim Couture','Statement Denim','Resort','Vacation Glam','Luxury Lounge','Athleisure','Sporty Glam','Avant-Garde','Couture-Inspired','Evening','Romantic','Bohemian','Western-Inspired','Retro','Modern Vintage','Y2K-Inspired','Alt','Goth','Preppy','Art-School Chic','Minimalist','Maximalist','Monochrome','Eclectic','Cozy Luxe')],
    ['top','TOP / BODICE','Upper silhouette','▱',o('Fashion tee','Graphic fashion tee','Baby tee','Boxy tee','Fitted tank','Ribbed tank','Corset-inspired top','Bustier top','Silk-look camisole','Silk-look blouse','Bow-neck blouse','Sheer layered blouse','Crisp button-down','Oversized button-down','Cropped button-down','Fine knit shell','Turtleneck','Mock-neck knit','Chunky sweater','Cropped sweater','Sweater vest','Cropped hoodie','Luxury hoodie','Tailored waistcoat','Longline waistcoat','Architectural top','Draped top','Off-shoulder knit','One-shoulder blouse','Peplum top','Wrap top','Halter top','Cape-sleeve top','Balloon-sleeve blouse','Ruffle blouse','Resort shirt','Bodysuit-inspired top','Denim shirt','Sculptural bustier over shirt','Sequined evening top','Metallic knit top','Asymmetrical tunic')],
    ['bottom','BOTTOM','Foundation piece','▰',o('Wide-leg trousers','Straight trousers','Cigarette trousers','Barrel trousers','Palazzo pants','Flared trousers','Pleated trousers','Paperbag-waist trousers','High-waist tailored pants','Low-rise tailored pants','Cargo trousers','Satin cargo pants','Parachute pants','Track pants','Relaxed tailoring','Bermuda shorts','Tailored shorts','Denim shorts','Leather-look shorts','Straight denim','Wide denim','Flared denim','Barrel denim','Baggy denim','Cropped denim','Distressed denim','Patchwork denim','Dark-wash jeans','Light-wash jeans','Denim maxi skirt','Denim midi skirt','Mini skirt','Midi skirt','Maxi skirt','Pencil skirt','Pleated skirt','Bubble skirt','Wrap skirt','Asymmetrical skirt','Column skirt','Tiered skirt','Slip skirt','Leather-look skirt','Cargo skirt')],
    ['onePiece','ONE-PIECE','Optional hero garment','▥',o('None','Utility jumpsuit','Tailored jumpsuit','Wide-leg jumpsuit','Boiler suit','Denim jumpsuit','Corseted jumpsuit','Cape jumpsuit','Relaxed romper','Tailored romper','Shirt dress','Wrap dress','Blazer dress','Column dress','Body-skimming midi dress','Fit-and-flare dress','Maxi dress','Tiered maxi dress','Sweater dress','Slip dress','Cowl-neck dress','Off-shoulder dress','One-shoulder dress','Cutout architectural dress','Sequin cocktail dress','Evening gown','Cape gown','Tuxedo dress','Sculptural dress','Kaftan-inspired dress','Surprise Me')],
    ['outerwear','LAYER / OUTERWEAR','Finish the silhouette','🧥',o('None','Tailored blazer','Double-breasted blazer','Oversized blazer','Cropped blazer','Tuxedo jacket','Cropped jacket','Denim jacket','Oversized denim jacket','Cropped denim jacket','Varsity jacket','Bomber','Cropped bomber','Moto jacket','Leather-look biker jacket','Shacket','Utility jacket','Safari jacket','Trench','Cropped trench','Patent-look trench','Wool coat','Wrap coat','Peacoat','Statement coat','Faux-fur statement coat','Long cardigan','Cropped cardigan','Duster','Cape','Capelet','Poncho','Puffer','Cropped puffer','Longline puffer','Quilted jacket','Sculptural outerwear','Sheer organza coat')],
    ['silhouette','SILHOUETTE','Shape & proportion','◒',o('Architectural volume','Relaxed column','Cropped over wide','Long over lean','Softly draped','Strong shoulder','Cinched and fluid','Oversized layering','Asymmetrical balance','Sculptural cocoon','Monumental tailoring')],
    ['material','MATERIAL','Hero textile','◈',o('Satin','Velvet','Denim','Suede','Leather-look','Knit','Silk-look','Plush','Tweed','Bouclé','Linen-look','Cotton','Jersey','Mesh','Lace','Crochet','Brocade','Jacquard','Organza','Chiffon','Metallic textile','Sequined textile','Quilted','Patent-look','Translucent layered textile')],
    ['fit','FIT','How it sits on her','↔',o('Body-skimming','Relaxed','Oversized','Tailored','Cinched waist','Draped','Cropped and boxy','Long and lean','Voluminous','Structured','Fluid','Mixed proportions')],
    ['garmentLength','GARMENT LENGTH','Hemline direction','↕',o('Cropped','Waist length','Hip length','Mini','Above knee','Knee length','Midi','Maxi','Floor sweeping','Mixed layered lengths')],
    ['layering','LAYERING','Build the outfit','▤',o('Single clean layer','Top under open shirt','Top under waistcoat','Shirt under knit','Blazer over bralette-style top','Jacket over hoodie','Coat over tailoring','Dress over fitted top','Sheer layer over opaque base','Double outerwear','Waist-tied layer','Unexpected three-piece layering')],
    ['pattern','PATTERN / TEXTURE','Surface interest','▧',o('Solid','Monochrome tonal','Pinstripe','Windowpane check','Plaid','Houndstooth','Polka dot','Graphic abstract','Color block','Marble print','Painterly floral','Oversized floral','Animal-inspired abstract','Camouflage-inspired','Patchwork','Embroidered','Beaded','Fringed','Pleated texture','Ribbed texture','Quilted texture','Surprise Me')],
    ['fashionColor','GARMENT COLOR','Outfit color family','◉',o('Black','Ivory','Espresso','Chocolate','Oxblood','Burgundy','Berry','Hot Pink','Blush','True Red','Burnt Orange','Saffron','Olive','Emerald','Teal','Cobalt','Navy','Lavender','Plum','Silver','Gold','Bronze','Denim Blue','Tonal Neutrals','Jewel-Tone Mix','Custom Palette Match')],
    ['footwear','FOOTWEAR','Never heels by default','👟',o('Fashion sneakers','Retro sneakers','Chunky sneakers','Dad sneakers','Platform sneakers','High-top sneakers','Low-profile sneakers','Slip-on sneakers','Sock sneakers','Running-inspired fashion sneakers','Canvas-inspired sneakers','Lace-up pumps','Classic pumps','D’Orsay pumps','Stilettos','Kitten heels','Block heels','Platform heels','Sculptural heels','Cone heels','Spool heels','Slingbacks','Mary Jane-inspired heels','Peep-toe heels','Ankle-strap heels','Ankle boots','Sock boots','Lace-up ankle boots','Western-inspired ankle boots','Combat boots','Mid-calf boots','Knee boots','Riding-inspired boots','Slouch boots','Platform boots','Over-knee fashion boots','Chelsea-inspired boots','Weather-ready fashion boots','Classic loafers','Penny-inspired loafers','Platform loafers','Heeled loafers','Backless loafers','Mules','Heeled mules','Ballet flats','Square-toe flats','Pointed fashion flats','Mary Jane-inspired flats','Fisherman sandals','Minimal strap sandals','Gladiator-inspired sandals','Platform sandals','Sport sandals','Slides','Wedges','Espadrille wedges','Clogs','Fuzzy lounge slides')],
    ['jewelry','EARRINGS + NECKLACE','Frame the face','◇',o('None','Minimal studs','Pearl-look studs','Crystal studs','Small hoops','Medium hoops','Statement hoops','Door-knocker earrings','Drop earrings','Chandeliers','Threader earrings','Sculptural earrings','Ear cuffs','Climber earrings','Fine chain','Snake chain','Curb chain','Rope chain','Layered necklaces','Single pendant','Locket','Choker','Statement collar','Tennis-style necklace','Pearl-look strand','Body chain accent','Mixed sculptural jewelry')],
    ['jewelryMaterial','JEWELRY MATERIAL','Metal & finish','✦',o('Gold-look','Silver-look','Rose-gold-look','Antique gold-look','Gunmetal-look','Pearl-look','Crystal','Colorful resin','Acrylic','Enamel','Wood + metal','Mixed material','Surprise Me')],
    ['wristwear','WRISTWEAR','Watches, cuffs, stacks','⌚',o('None','Delicate bracelet','Tennis-style bracelet','Stacked bangles','Wide sculptural cuff','Mixed bracelet stack','Classic watch','Minimal watch','Statement watch','Watch + bangles','Upper-arm cuff','Surprise Me')],
    ['rings','RINGS','Hand styling','◌',o('None','Single signet ring','Delicate band stack','Cocktail ring','Stacked rings','Mixed statement rings','Thumb ring accent','Two-hand ring story','Surprise Me')],
    ['accessory','ACCESSORY','The finishing move','👜',o('Quilted top-handle bag','Structured tote','Crossbody','Mini bag','Bucket bag','Weekender','Travel bag','Oversized sunglasses','Optical frames','Statement belt','Silk-look scarf','Head scarf','Beret','Wide-brim hat','Fashion gloves','None')],
    ['prop','PROP STORY','Useful, not cluttered','☕',o('None','Surprise Me','Coffee cup','Drink cup','Shopping bags','Luggage','Weekender','Flowers','Bouquet','Books','Magazine','Laptop','Tablet','Phone','Camera','Headphones','Planner','Art supplies','Makeup kit','Lip gloss','Perfume','Keys','Birthday cake','Balloons','Gift boxes','Gym equipment','Salon tools','Vanity mirror','Studio light','Single Hero Prop','Prop Cluster')]
  ],
  attitude:[
    ['attitude','ATTITUDE','Her energy','⚡',o('Unbothered','Petty','Bougie','Sweet But Don’t Try Me','Bossy','Spoiled','Playful','Flirty','Quiet Luxury','Loud & Proud','Main Character','Soft Life','Independent','Pretty & Problematic','Classy With a Mouth','Grown & Dangerous','Chill Until Provoked','Booked & Busy','I Said What I Said','Joyfully Extra','Cool Without Trying','Minding My Business','Don’t Start None','Soft But Serious','Funny & Fine','Confidently Weird','Grown & Gorgeous')],
    ['expressionCategory','EXPRESSION CATEGORY','Choose the kind of face card','☺',EXPRESSION_CATEGORIES],
    ['expression','EXPRESSION','Specific facial performance','◉',ALL_EXPRESSIONS],
    ['poseCategory','POSE CATEGORY','Choose the movement family','♟',POSE_CATEGORIES],
    ['pose','POSE / ACTION','Specific anatomically plausible action','💃🏾',ALL_POSES],
    ['typeInteraction','TYPE INTERACTION','Move through the words','Aa',o('None','Stepping through typography','Leaning against typography','Sitting on letters','Peeking around letters','Emerging through letters','Walking through typography','Wrapping around type','Type orbiting character','Character interrupting letters')]
  ],
  art:[
    ['artStyle','ART STYLE','Signature or switch it up','🎨',o('Semi-Realistic Chibi','Fashion Chibi','High-Fashion Chibi','Glossy 3D Chibi','Soft 3D Chibi','Dimensional Chibi','Stylized Realism','Semi-Realistic Illustration','Hyperrealistic-Inspired Character Art','Editorial Fashion Illustration','Luxury Editorial Illustration','Magazine Illustration','Painterly Glam','Oil-Painted Look','Acrylic-Painted Look','Gouache Look','Watercolor Fashion Illustration','Colored-Pencil Fashion Illustration','Soft Pastel Illustration','Glossy 3D Character Art','Faux 3D','Faux 4D','Faux 5D','Dimensional Cartoon Glam','Editorial Doll-Like Art','Pop Editorial','Pop Art','Bold Graphic Illustration','Vector-Inspired Illustration','Sticker Illustration','Retro Glam Illustration','Vintage Beauty Illustration','1970s Glam','1980s Editorial','1990s Fashion Illustration','Y2K-Inspired Art','Comic-Inspired Glam','Graphic-Novel Glam','Mixed-Media Fashion Collage','Paper-Cut Dimensional Art','Dreamy Glam','Surreal Fashion Art','Fantasy Glam','Celestial Glam','Futuristic Character Art','Cyber Glam','Afrofuturist-Inspired Original Art Direction','Luxury Street Editorial','Beauty Campaign Illustration','DTF Apparel Illustration')],
    ['palette','COLOR STORY','Campaign palette','◉',o('Oxblood + Blush + Champagne','Espresso + Ivory + Gold','Midnight + Cobalt + Chrome','Olive + Terracotta + Cream','Plum + Rose + Copper','Monochrome Cocoa','Black + Hot Pink + Pearl','Teal + Saffron + Onyx','Lavender + Wine + Silver','Denim Blue + Caramel + Red','Emerald + Chocolate + Gold','Citrus + Lilac + Espresso','Custom Palette')],
    ['composition','COMPOSITION','Visual architecture','▦',o('Centered monument','Editorial asymmetry','Full-body campaign','Layered depth','Diagonal motion','Low-angle hero','Close beauty crop','Wide environmental portrait','Graphic cutout collage','Circular portal','Stacked poster composition')],
    ['designArchitecture','DESIGN BLUEPRINT','Give every build its own layout logic','◇',DESIGN_ARCHITECTURES],
    ['subjectPlacement','SUBJECT PLACEMENT','Where she owns the frame','▣',SUBJECT_PLACEMENTS],
    ['detailPlacement','DETAIL PLACEMENT','Keep supporting elements separated','✦',DETAIL_PLACEMENTS],
    ['visualDensity','VISUAL DENSITY','Clean space versus controlled richness','◫',VISUAL_DENSITIES],
    ['camera','CAMERA / CROP','How we see her','◉',o('Eye-level full body','Low-angle full body','Three-quarter portrait','Waist-up editorial','Close beauty portrait','Wide cinematic frame','Candid side angle','Dynamic dutch angle','Telephoto compression')],
    ['lighting','LIGHTING','Set the glow','☀',o('Berry rim light','Soft studio beauty light','Golden-hour warmth','Hard editorial flash','Neon edge light','Window light','Moody chiaroscuro','High-key campaign light','Colored gel lighting','Candlelit luxury')],
    ['atmosphere','ATMOSPHERE','Mood in the air','✦',o('Clean editorial','Soft haze','Champagne spark dust','Rain-slick reflections','Dreamlike glow','Graphic shadows','Cinematic smoke','Sunlit warmth','Night-city energy','Playful studio set')],
    ['background','BACKGROUND','Scene direction','▧',o('Match Production Mode','Transparent-Background Aesthetic','Minimal Scene','Full Lifestyle Scene','Soft Abstract Environment')],
    ['includeTypography','MATCHING TYPOGRAPHY?','Do you want words in the artwork?','Aa',o('Yes — Match the Vibe','No — Image Only')],
    ['typography','TYPOGRAPHY STYLE','Pick a style or let the generator decide','Aa',o('Let the Generator Pick','Small Editorial Accent','Bubble Type','Ribbon Type','Portal Type','Runway Type','Frame Type','Orbiting Type','Sculptural Type','Interlocking Type','Graffiti-Inspired Type','Couture Editorial Type','Stacked Monument Type','Chrome Type','Plush Type','Crystal Type','Handwritten Accent','Retro Display Type','Bold Block Type','Soft Rounded Type')],
    ['exactPhrase','EXACT PHRASE','Preserved verbatim','✎','text'],
    ['customPalette','CUSTOM PALETTE','Three exact colors','◉','colors']
  ],
  production:[
    ['productionMode','PRODUCTION MODE','Final use','⚙',o('Regular Artwork','DTF / Shirt Artwork','Sticker')],
    ['detail','DETAIL LEVEL','Control the finish','✦',o('Clean & Minimal','Balanced','Rich Detail','Maximalist but Controlled')],
    ['outputShape','OUTPUT SHAPE','Working canvas','▣',o('Portrait 4:5','Square 1:1','Landscape 3:2','Tall Poster 2:3','Wide Banner 16:9')],
    ['qualityNotes','PRODUCTION NOTES','Optional constraints','✎','text']
  ]
};
export const QUICK_FIELDS=new Set(['world','footballMode','teamPaletteType','teamColors','gameDayHair','gameDayMakeup','gameDayTop','gameDayFootwear','gameDayAttitude','gameDayExpression','gameDayPose','gameDayEnvironment','gameDayArtStyle','gameDayPhrase','gameDayProduction','holiday','holidayVibe','holidayIntensity','age','body','complexion','hairFamily','makeup','fashionDirection','footwear','attitude','expressionCategory','expression','poseCategory','pose','artStyle','palette','includeTypography','typography','exactPhrase','productionMode','background']);
export const defaults={world:'Street Luxury Baddie',...gameDayDefaults,holiday:'None',holidayResolved:'None',holidayVibe:'Surprise Me',holidayIntensity:'Subtle Nod',holidayPalette:'Match Main Color Story',holidayFashion:'None',holidayProps:'None',holidayEnvironment:'Match Existing Background',holidayTypography:'Use Existing Typography Settings',holidayPhrase:'',holidayBeauty:'None',holidayCustomPalette:['#6e2034','#e89a9a','#d0a05d'],age:'30s',body:'Soft Curvy',complexion:'Rich Mahogany',bodyArt:'Delicate Fine-Line Tattoo',occasion:'Brunch',height:'Average height',piercings:'Classic ear piercings',hairFamily:'Locs',hairStyle:'Half-up crown',hairLength:'Waist Length',texture:'Loc texture',hairColor:'Natural Black',faceShape:'Oval',eyes:'Almond eyes + arched brows',makeup:'Soft Glam',nails:'Medium almond',beautyDetails:'Beauty mark',fashionDirection:'Grown Woman Streetwear',top:'Fine knit shell',bottom:'Wide-leg trousers',onePiece:'None',outerwear:'Oversized blazer',silhouette:'Cropped over wide',material:'Leather-look',fit:'Relaxed',garmentLength:'Mixed layered lengths',layering:'Top under waistcoat',pattern:'Solid',fashionColor:'Oxblood',footwear:'Fashion sneakers',jewelry:'Layered necklaces',jewelryMaterial:'Gold-look',wristwear:'Watch + bangles',rings:'Stacked rings',accessory:'Quilted top-handle bag',prop:'Coffee cup',attitude:'Unbothered',expressionCategory:'Smirks & Sass',expression:'Knowing smirk',poseCategory:'Seated & Perched',pose:'Seated lean',typeInteraction:'Leaning against typography',artStyle:'Luxury Street Editorial',palette:'Oxblood + Blush + Champagne',composition:'Centered monument',designArchitecture:'Clean Editorial Spread',subjectPlacement:'Offset Left',detailPlacement:'Edge Anchors',visualDensity:'Airy',camera:'Eye-level full body',lighting:'Berry rim light',atmosphere:'Rain-slick reflections',background:'Full Lifestyle Scene',includeTypography:'Yes — Match the Vibe',typography:'Stacked Monument Type',exactPhrase:'',customPalette:['#6e2034','#e89a9a','#d0a05d'],productionMode:'Regular Artwork',detail:'Rich Detail',outputShape:'Portrait 4:5',qualityNotes:''};
export const allFieldEntries=()=>Object.values(FIELDS).flat();
export const optionsFor=(key)=>allFieldEntries().find(f=>f[0]===key)?.[4]||[];
