export const EXPRESSION_GROUPS={
  'Soft & Warm':['Soft smile','Closed-lip smile','Gentle grin','Warm welcoming smile','Shy smile','Tender smile','Proud smile','Dimpled smile','Peaceful expression','Serene gaze','Contented glow','Soft eyes + relaxed mouth'],
  'Joy & Laughter':['Big smile','Full laugh','Caught mid-laugh','Belly laugh','Laughing with eyes closed','Breathless laugh','Joyful grin','Delighted gasp','Happy tears','Playful giggle','Head-back laugh','Can’t-stop-laughing expression'],
  'Smirks & Sass':['Knowing smirk','Satisfied smirk','Crooked smirk','Petty smirk','Smug little smile','Playful smirk','Mischievous grin','Secretive smile','I-know-something smirk','Barely amused','Confident half-smile','Sweet smile + sharp energy'],
  'Side-Eye & Skepticism':['Side-eye','Dramatic side-eye','Raised brow','Double raised brow','Skeptical','Suspicious glance','Doubtful stare','Unimpressed','Over-it','Be-serious expression','Are-you-done look','Disbelieving squint'],
  'Cool & Composed':['Deadpan','Neutral editorial gaze','Serene','Poised','Stoic','Calm confidence','Reserved expression','Bored','Cool without trying','Minding-my-business gaze','Quiet luxury composure','Unbothered calm'],
  'Commanding & Powerful':['Focused','Commanding','Fierce gaze','Determined','Boss stare','Chin-lifted confidence','Intense eye contact','Victory expression','Protective confidence','Challenge accepted','Direct-to-camera power gaze','Controlled authority'],
  'Flirty & Romantic':['Coy','Flirty','Playful pout','Soft pout','Dreamy gaze','Bashful smile','Affectionate gaze','Come-here glance','Romantic softness','Teasing smile','Lovestruck but composed','Soft face + confident eyes'],
  'Surprised & Reactive':['Shocked','Surprised','Caught off guard','Wide-eyed disbelief','Delighted surprise','Speechless','Dramatic gasp','Wait-what expression','Unexpectedly impressed','Curious surprise','Startled but stylish','Pleasantly stunned'],
  'Moody & Dramatic':['Irritated','Annoyed','Frustrated','Moody','Tearful but composed','Emotional restraint','Sweet face / dangerous eyes','Quietly furious','Dramatic exhale','Melancholy gaze','Deep in thought','Don’t-push-me expression'],
  'Editorial & Beauty':['Beauty campaign gaze','Eyes gently closed','Profile gaze','Parted-lip editorial expression','Graphic-liner focus','Lip-focused beauty pose','Over-the-shoulder beauty gaze','High-fashion blank stare','Avant-garde intensity','Camera-aware editorial stare','Sculptural profile expression','Luxury fragrance-campaign gaze']
};

export const POSE_GROUPS={
  'Standing & Power':['Power stance','Contrapposto','Hands in pockets','Arms folded','One hand in pocket','Hands on hips','One hand on hip','Feet planted wide','Strong shoulder stance','Chin lifted','Relaxed upright stance','Weight shifted to one hip','Standing with ankles crossed','Jacket held over shoulder','Hands clasped in front','Hands clasped behind back'],
  'Walking & Movement':['Runway stride','Walking toward camera','Walking away','Looking back while walking','Mid-step turn','Street-style stride','Crosswalk stride','Slow confident walk','Power walk with bag','Coat moving in stride','Descending stairs','Ascending stairs','Stepping off curb','Turning a corner','Walking through doorway','Wind-swept walking pose'],
  'Seated & Perched':['Cross-legged sitting','Seated lean','Perched on stool','Sitting on floor','Chair power pose','Sideways chair sit','Sitting with ankles crossed','Elbow resting on knee','One leg extended while seated','Perched on desk edge','Sitting on counter','Seated with bag in lap','Seated profile pose','Sitting backward on chair','Bench-side lean','Car-seat editorial pose'],
  'Lounging & Reclining':['Reclining','Lounging','Side recline','Chaise lounge pose','Couch corner lounge','Head resting on hand','Legs draped over chair arm','Relaxed floor lounge','Poolside lounge','Bed-edge relaxed pose','Sun-chair recline','Luxury lobby lounge','Soft curled-up lounge','One-arm-back recline'],
  'Floor & Low-Level':['Sitting with knees bent','One knee raised floor pose','Crouched editorial pose','Low squat fashion pose','Kneeling upright','One-knee-down pose','Floor lean against wall','Seated on steps','Crouched with elbow on knee','Low-angle grounded stance','Floor pose with legs to side','Compact editorial crouch'],
  'Dynamic & Dance':['Mid-twirl','Dancing','Hair flip','Laughing in motion','Jacket toss','Skirt-swish movement','Confident spin','One-arm-up dance pose','Shoulder groove','Step-touch movement','Celebratory jump','Turning with fabric motion','Playful kick-back','Rhythmic walking dance','Hands-up celebration','Caught mid-groove'],
  'Editorial & Fashion':['Shoulder turn','Looking back','Sculptural arm pose','Asymmetrical fashion pose','Elongated editorial stance','Hand framing face','Angular elbow pose','Coat-open reveal','Garment-adjusting pose','One shoulder dropped','Profile fashion pose','Back-to-camera editorial pose','Leaning into negative space','Silhouette-first pose','Fabric-held-out pose','Low-angle campaign pose'],
  'Portrait & Beauty':['Hand under chin','Fingertips at jawline','Hand near cheek','Face-framing hands','Over-shoulder portrait','Three-quarter beauty pose','Direct front portrait','Eyes-closed beauty pose','Hair swept to one side','Necklace-touch portrait','Collar-adjusting portrait','Sunglasses-lowered gaze','Chin-on-fist portrait','Soft profile portrait'],
  'Beauty & Grooming':['Adjusting sunglasses','Fixing earring','Applying lip gloss','Checking makeup mirror','Smoothing edges','Adjusting head scarf','Fluffing afro','Arranging locs','Checking nails','Applying perfume','Fastening bracelet','Putting on lipstick','Adjusting necklace','Pinning hair accessory'],
  'Lifestyle & Work':['Using laptop','Working at desk','Writing in planner','Reading','Reviewing documents','Taking a phone call','Voice-note recording','Creative sketching','Standing at presentation board','Coffee-break lean','Typing on tablet','Organizing studio tools','Packing an order','Opening boutique door','Reviewing a mood board','Boss-at-desk pose'],
  'Prop Interaction':['Holding coffee','Carrying bouquet','Holding purse','Opening handbag','Holding magazine','Holding camera','Holding perfume bottle','Carrying gift box','Holding shopping bags','Holding drink glass','Holding compact mirror','Holding birthday cake','Holding art supplies','Leaning on luggage','Using headphones','Holding flowers at side'],
  'Travel & Shopping':['Pulling luggage','Rolling suitcase walk','Airport lounge pose','Holding boarding pass','Carrying weekender bag','Hotel check-in pose','Looking at travel phone','Boutique browsing','Shopping rack interaction','Carrying multiple bags','Window-shopping pause','Escalator travel pose','Cab-side luggage pose','Resort arrival stance'],
  'Social & Celebration':['Making a toast','Clinking glass toward camera','Blowing a kiss','Waving hello','Opening a gift','Cutting celebration cake','Holding flowers proudly','Hands clasped in excitement','Confetti reaction','Birthday wish pose','Brunch cheers pose','Victory hand raise','Celebratory shoulder lean','Group-photo-ready solo pose'],
  'Street & Architecture':['Leaning against wall','Leaning against railing','Standing in doorway','Sitting on stoop','Leaning on street barrier','Pose beside window','Against elevator wall','Sitting on architectural ledge','One foot against wall','Framed by doorway','Walking under archway','Leaning on column','Staircase power pose','Corner-wall editorial pose'],
  'Typography Interaction':['Stepping through typography','Leaning against typography','Sitting on letters','Peeking around letters','Emerging through letters','Walking through typography','Wrapping around type','Type orbiting character','Character interrupting letters','Standing inside letter portal','Holding sculptural letterform','Parting stacked letters','Resting arm on typography','Casting shadow across type']
};

export const EXPRESSION_CATEGORIES=['Surprise Me',...Object.keys(EXPRESSION_GROUPS)];
export const POSE_CATEGORIES=['Surprise Me',...Object.keys(POSE_GROUPS)];
const unique=items=>[...new Set(items)];
export const ALL_EXPRESSIONS=['Surprise Me',...unique(Object.values(EXPRESSION_GROUPS).flat())];
export const ALL_POSES=['Surprise Me',...unique(Object.values(POSE_GROUPS).flat())];
export const expressionOptionsFor=category=>category==='Surprise Me'?ALL_EXPRESSIONS:['Surprise Me',...(EXPRESSION_GROUPS[category]||ALL_EXPRESSIONS.slice(1))];
export const poseOptionsFor=category=>category==='Surprise Me'?ALL_POSES:['Surprise Me',...(POSE_GROUPS[category]||ALL_POSES.slice(1))];
